language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

branches:
  only:
    - master
    - development

stages:
  - name: test
  - name: test-to-stop
  - name: build-deploy
    if: branch = master AND type = push

before_install:
  - openssl aes-256-cbc -K $encrypted_bf9db7fc2d2b_key -iv $encrypted_bf9db7fc2d2b_iv
    -in ./travis/deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: test
      script:
        - make install
        - make test
    - stage: build-deploy
      script:
        - make build-image
        - make push-image
        - make deploy