version: "3.7"

x-nodejs:
  &nodejs
  image: "node:11"
  volumes:
    - ./:/app
  working_dir: '/app'

services:
  nodejs-watch:
    <<: *nodejs
    ports:
      - "80:80"
    command: yarn run watch

  nodejs:
    <<: *nodejs