version: "3.7"

x-nodejs:
  &nodejs
  image: "node:11"
  volumes:
    - ./:/app
  working_dir: '/app'
  networks:
    - shinkasen-travel

services:
  nodejs-watch:
    <<: *nodejs
    ports:
      - "80:3000"
    command: yarn run watch
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT

  nodejs-http:
    <<: *nodejs
    ports:
      - "80:3000"
    command: yarn run prod
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
#    labels:
#      - traefik.docker.network

  nodejs:
    <<: *nodejs

  mongo:
    image: "mongo:4.0.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - shinkasen-travel
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
    networks:
      - shinkasen-travel

networks:
  shinkasen-travel:
    name: shinkasen-travel

volumes:
  mongo:
    name: mongo