version: "3.7"

x-nodejs:
  &nodejs
  image: "node:11"
  volumes:
    - ./:/app
  working_dir: '/app'
  networks:
    - shinkasen

services:
  nodejs-watch:
    <<: *nodejs
    ports:
      - "80:3000"
    command: yarn run watch

  nodejs-http:
    <<: *nodejs
    ports:
      - "80:3000"
    command: yarn run prod

  nodejs:
    <<: *nodejs

  mongo:
    image: "mongo:4.0.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - shinkasen

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    networks:
      - shinkasen

networks:
  shinkasen:
    driver: bridge