version: "3.7"

x-nodejs:
  &nodejs
  image: "node:11"
  volumes:
    - ./:/app
  working_dir: '/app'
  networks:
    - shinkansen
    - shinkansen-travel

services:
  nodejs-watch:
    <<: *nodejs
    command: yarn run watch
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
    labels:
      - "traefik.frontend.rule=Host:shinkansen-travel.lissenburg.test"
      - "traefik.port=3000"

  nodejs-http:
    <<: *nodejs
    command: yarn run prod
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
    labels:
      - "traefik.frontend.rule=Host:shinkansen-travel.lissenburg.test"
      - "traefik.port=3000"

  nodejs:
    <<: *nodejs

  mongo:
    image: "mongo:4.0.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - shinkansen-travel
    volumes:
      - mongo:/data/db
    labels:
      - "traefik.enable=false"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
    networks:
      - shinkansen-travel
    labels:
      - "traefik.enable=false"
      -
  #Should be moved to external repo
  proxy:
    image: "traefik:v1.7.14"
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shinkansen


networks:
#  shinkansen:
#    external: true
  shinkansen:
    name: shinkansen
  shinkansen-travel:
    name: shinkansen-travel

volumes:
  mongo:
    name: mongo