apiVersion: v1
kind: Service
metadata:
  name: shinkansen-travel-mongodb-service
  labels:
    app: shinkansen-travel
    service: mongodb
spec:
  type: ClusterIP
  ports:
    - targetPort: 27017
      port: 27017
  selector:
    app: shinkansen-travel
    service: mongodb