apiVersion: v1
kind: Service
metadata:
  name: shinkansen-travel-node-http-service
  labels:
    app: shinkansen-travel
    service: http
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30001
  selector:
    app: shinkansen-travel
    service: http