apiVersion: v1
kind: Pod
metadata:
  name: shinkansen-travel-node-http-pod
  labels:
    app: shinkansen-travel
    service: http
spec:
  containers:
    - name: node-http
      image: lissenburg/shinkansen-travel-node-http
      env:
        - name: MONGODB_HOST
          value: shinkansen-travel-mongodb-service
        - name: MONGODB_PORT
          value: '27017'
      envFrom:
        - secretRef:
            name: shinkansen-travel-mongodb-secret