version: "3.7"

services:
  node-http:
    image: lissenburg/shinkansen-travel-node-http
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
    networks:
      - shinkansen
      - shinkansen-travel
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:shinkansen-travel.lissenburg.nl"

  mongo:
    image: "mongo:4.0.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - shinkansen-travel
    labels:
      - "traefik.enable=false"
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: "traefik:v1.7"
    command: --api
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - shinkansen
    deploy:
      placement:
        constraints: [node.role == manager]

  rabbitmq:
    image: "rabbitmq:3.7-management"
    hostname: shinkansen
    ports:
      - 8082:15672
    networks:
      - shinkansen
    labels:
      - "traefik.enable=false"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  shinkansen:
    name: shinkansen
  shinkansen-travel:
    name: shinkansen-travel