version: "3.7"

services:
  node-http:
    image: lissenburg/shinkansen-travel-node-http
    ports:
      - 80:3000
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
    networks:
      - shinkasen

  mongo:
    image: "mongo:4.0.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - shinkasen

networks:
  shinkasen:
    driver: bridge