version: "3.7"

services:
  app:
    image: lissenburg/shinkansen-travel-node-http
    ports:
      - 80:3000
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - shinkasen

  mongo:
    image: "mongo:4.0.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - shinkasen

networks:
  shinkasen:
    driver: bridge